"""
Executes the full pipeline for a request.
"""
import logging
from core.models.shorts_models import ProcessingRequest, ProcessingResult, ProcessingStatus
from engines.shorts_generator_engine.managers.workflow_launcher import WorkflowLauncher
from engines.shorts_generator_engine.managers.highlight_selection_manager import HighlightSelectionManager
from engines.shorts_generator_engine.managers.caption_placement_manager import CaptionPlacementManager
from engines.shorts_generator_engine.managers.timeline_preparation_manager import TimelinePreparationManager
from engines.shorts_generator_engine.managers.project_assembler import ProjectAssembler

logger = logging.getLogger(__name__)

class ProcessingPipeline:
    def __init__(
        self,
        workflow_launcher: WorkflowLauncher,
        highlight_selector: HighlightSelectionManager,
        caption_placer: CaptionPlacementManager,
        timeline_prep: TimelinePreparationManager,
        project_assembler: ProjectAssembler
    ):
        self.launcher = workflow_launcher
        self.highlight_selector = highlight_selector
        self.caption_placer = caption_placer
        self.timeline_prep = timeline_prep
        self.project_assembler = project_assembler
        
    async def process(self, request: ProcessingRequest) -> ProcessingResult:
        result = ProcessingResult(request_id=request.request_id, status=ProcessingStatus.ANALYZING)
        
        def report_progress(msg, pct):
            if request.progress_callback:
                request.progress_callback(msg, pct)
                
        def check_cancelled():
            if request.is_cancelled and request.is_cancelled():
                raise Exception("Workflow Cancelled by User")
        
        try:
            report_progress("Validating Configuration...", 5)
            # Configuration Validation
            if not request.video_paths:
                raise Exception("No video paths provided.")
                
            for video_path in request.video_paths:
                check_cancelled()
                report_progress(f"Starting Analysis for {video_path.name}", 10)
                
                result.stage_statuses["M6_ANALYSIS"] = "RUNNING"
                wf_results = await self.launcher.launch_for_video(request, video_path)
                result.stage_statuses["M6_ANALYSIS"] = "COMPLETED"
                
                check_cancelled()
                report_progress("Selecting Highlights...", 30)
                
                raw_captions = wf_results.get("generate_captions", {})
                raw_highlights = wf_results.get("extract_highlights", {})
                
                clips = self.highlight_selector.select_highlights(raw_highlights, video_path, request.settings)
                
                check_cancelled()
                report_progress("Creating Editing Timeline...", 50)
                
                # Apply M7 Editing Decisions
                result.stage_statuses["M7_EDITING"] = "RUNNING"
                from engines.editing_engine.editing_engine import EditingEngine
                editing_engine = EditingEngine()
                editing_engine.initialize()
                editing_engine.generate_editing_decisions(clips, request.settings)
                result.stage_statuses["M7_EDITING"] = "COMPLETED"
                
                check_cancelled()
                report_progress("Assigning Captions...", 60)
                
                result.stage_statuses["M8_CAPTIONS"] = "RUNNING"
                if raw_captions:
                    clips = self.caption_placer.assign_captions(clips, raw_captions)
                    result.stage_statuses["M8_CAPTIONS"] = "COMPLETED"
                else:
                    result.stage_statuses["M8_CAPTIONS"] = "SKIPPED (No speech detected)"
                
                check_cancelled()
                report_progress("Preparing Project Assembly...", 70)
                timeline = self.timeline_prep.prepare_timeline(clips, request.settings)
                project = self.project_assembler.assemble(timeline, request.settings)
                
                # Retrieve the XML data generated by PremiereEngine
                xml_data = wf_results.get("build_timeline", {}).get("xml_data")
                if xml_data:
                    project._xml_data = xml_data
                
                # Attach request callbacks so OutputManager can use them
                project._progress_callback = request.progress_callback
                project._is_cancelled = request.is_cancelled
                
                result.projects.append(project)
                
            result.status = ProcessingStatus.COMPLETED

            
        except Exception as e:
            logger.error(f"Pipeline failed: {e}")
            result.status = ProcessingStatus.FAILED
            result.error = str(e)
            
        return result
